### ISSUE TITLE
Not showing all undolevels

### ISSUE THREAD

**Issue by soer9459** [debugloop/telescope-undo.nvim#49] opened 2024-03-31 05:43 UTC
Hi

When comparing this plugin and mbbill undotree, I am able to see a much longer list of file states in undotree compared to telescope undo. I couldn't seem to find a configuration item for this?

**Comment by debugloop** [comment] 2024-03-31 06:17
Not sure how that would happen, this plugin uses the complete `:undolist`. Can you compare the output of that with what your seeing on both plugins? Are the state numbers in telescope-undo continuous and without gaps too?

Also, I'm going to need a reproducible case where the two diverge. Can you provide a series of inputs to conjure a file? I.e. `iline one<esc>oline two<esc>yypA1<esc>`...

However, I can't imagine how this happens, as both plugins use the undolist built in and just render that.

**Comment by soer9459** [comment] 2024-03-31 06:54
Took some screenshots.
It does appear that the list in telescopeundo is not continuous

Heres the last state in undotree and telescopeundo compared:
<img width="1772" alt="Screenshot 2024-03-31 at 08 51 04" src="https://github.com/debugloop/telescope-undo.nvim/assets/44211835/623ea915-c12b-4f42-9aad-6097d6783e77">

And here state 1288 - 1292 is missing somehow. These states do appear in undotree
<img width="1772" alt="Screenshot 2024-03-31 at 08 52 31" src="https://github.com/debugloop/telescope-undo.nvim/assets/44211835/c619a084-8e77-4993-9d4a-438dac493009">

**Comment by soer9459** [comment] 2024-03-31 07:03
I can reproduce by creating a file, and writing something like "Hello".
I pasted the line ~370 times, and and the looks at the undo history in both plugins.

Undotree goes to 0, and telescope-undo only goes to 121
<img width="1772" alt="Screenshot 2024-03-31 at 09 03 05" src="https://github.com/debugloop/telescope-undo.nvim/assets/44211835/1e3f17de-2421-4527-b137-b7b16be2d230">

**Comment by debugloop** [comment] 2024-03-31 07:41
I'm on vacation and can test it out myself right now. Some further things you can try:

- At the bottom, your screenshots show that the buffer is not modifiable -> that will lead to telescope-undo exiting without doing anything further. Why is your buffer not modifiable? Maybe this is some strange behaviour from having the undo tree focused?
- If you have branches, it is correct that you don't have some states in linear order. They should be all accounted for inside a subtree.
- Did you compare to `:undolist` as well?
- Can you find an undostate at position 50 when you do your 350 undostates example? You'd have to sneak in a `world` in your hello example at one of the early positions that you can search for.
- Do you have some sort of result limiter as part of your telescope config? It's possible that something like this exists and has been configured. It's not a nvim/telescope default though.

**Comment by soer9459** [comment] 2024-03-31 07:49
> * Can you find an undostate at position 50 when you do your 350 undostates example? You'd have to sneak in a `world` in your hello example at one of the early positions that you can search for.
> * Do you have some sort of result limiter as part of your telescope config? It's possible that something like this exists and has been configured. It's not a nvim/telescope default though.

Arh, yes i can. I don't have anything to limit the list configured in telescope, but that may be the issue then

Heres my config
```
return {
	'nvim-telescope/telescope.nvim',
	dependencies = {
		'nvim-lua/plenary.nvim',
		'nvim-telescope/telescope-file-browser.nvim',
		'debugloop/telescope-undo.nvim',
		{
			'nvim-telescope/telescope-fzf-native.nvim',
			build = 'make',
		},
	},
	config = function()
		local ts = require('telescope')
		local ts_undo = require('telescope-undo.actions')
		ts.setup {
			defaults = {
				borderchars = { '─', '│', '─', '│', '┌', '┐', '┘', '└' },
				layout_strategy = 'horizontal',
				sorting_strategy = 'ascending',
				layout_config = {
					prompt_position = 'top',
					width = 0.8,
					height = 0.8,
					preview_width = 0.5,
				},
			},
			pickers = {
				find_files = {
					find_command = {
						'fd',
						'--type',
						'f',
						'-H',
						'--strip-cwd-prefix',
					}
				}
			},
			extensions = {
				file_browser = {
					hijack_netrw = true,
					hide_parent_dir = true,
					hidden = {
						file_browser = false,
						folder_browser = false,
					},
					display_stat = { },
					mappings = {
						['n'] = {
							['-'] = ts.extensions.file_browser.actions.goto_parent_dir,
							['<BS>'] = ts.extensions.file_browser.actions.goto_parent_dir,
							-- KEYBIND TO OPEN SELECTED FILES
						},
					}
				},
				undo = {
					mappings = {
						i = {
							['<cr>'] = ts_undo.restore,
							['<C-cr>'] = ts_undo.restore,
							['<C-y>'] = ts_undo.yank_deletions,
							['<C-r>'] = ts_undo.yank_additions,
						},
						n = {
							['y'] = ts_undo.yank_additions,
							['r'] = ts_undo.yank_deletions,
							['<cr>'] = ts_undo.restore,
						},
					},
				}
			}
		}
		ts.load_extension('file_browser')
		ts.load_extension('fzf')
		ts.load_extension('undo')
	end,
}
```

**Comment by debugloop** [comment] 2024-03-31 08:37
Seems you found the culprit in that other issue, yes 👍🏻 I read through your config, looking good, nothing out of the ordinary. I assume my nvim would behave the same way if I could check it right now.

Thanks for reporting and thus documenting this here, but I'm going to close this for now until there's something actionable :)

I know once noticed stuff like this can be nagging, but in all honesty: There should not be a scenario where you need more that those 250ish undo states since your last git commit 😅 Especially since searching still works, too ;)

**Closed by debugloop** 2024-03-31 08:37 UTC

**Comment by soer9459** [comment] 2024-03-31 19:07
> Seems you found the culprit in that other issue, yes 👍🏻 I read through your config, looking good, nothing out of the ordinary. I assume my nvim would behave the same way if I could check it right now.
> 
> Thanks for reporting and thus documenting this here, but I'm going to close this for now until there's something actionable :)
> 
> I know once noticed stuff like this can be nagging, but in all honesty: There should not be a scenario where you need more that those 250ish undo states since your last git commit 😅 Especially since searching still works, too ;)

Yes, that seems to be it. I don't think it'll ever be a "real" issue, but sometimes you notice something that nags you anyway,even if irrational :)

Thank you for the quick replies
