### ISSUE TITLE
<CR> results only in new blank buffer

### ISSUE THREAD

**Issue by Aaronik** [debugloop/telescope-undo.nvim#16] opened 2023-01-02 01:44 UTC
Hello,

Thanks for your work here, I've been exploring undo trees and I like yours the best.

However, there's a critical issue I'm facing which makes it impossible for me to reasonably use this.

Say I have a file I've been working on that has an undo history. I call `:Telescope undo`, and I see the telescope window pop up with the whole undo tree, fuzzy searchable, snappy, looking great.

I enter normal mode within the telescope prompt (and this is a clean telescope install, no config), navigate to my desired entry, and press `<CR>`. What I expect is for the additions from that entry to be copied to my default register, but what happens instead is that a new empty buffer is created, with the title of the entry I selected, something like `state #1386, -1, 2 days ago`, and nothing is added to my default register.

Am I doing something wrong in the configuration here?  

EDIT: Put some quotes around `<CR>` which didn't show up

**Comment by debugloop** [comment] 2023-01-02 12:10
I think the issue is that I don't provide a mapping in normal mode at all, as I only use telescope in insert mode, i.e. scrolling with C-n, C-p. What your describing is the telescope default action.

If you start from the default config provided in the README, you should be able to copy the `i =` section to a `n =` section in the same block (or rename, if you don't intend to use insert mode telescope).

What normal mode mappings would you suggest I should include in the default, other than yank additions as default <cr> action? For yank deletions and goto state specifically?

**Comment by Aaronik** [comment] 2023-01-02 18:24
> I think the issue is that I don't provide a mapping in normal mode at all, as I only use telescope in insert mode, i.e. scrolling with C-n, C-p. What your describing is the telescope default action.

This is how I want to use it, but there's been a persistent issue with my setup that prevents `<CR>` and variants from working in insert mode in telescope for me. It's been quite frustrating, I've just been kind of living with it. One of those things that's a little annoying but not so much that it's warranted hunting down the issue, b/c I can just press `<ESC>` once and it's fixed.

But, after seeing your response, I felt invigorated to figure out what's going on with my setup. And I did!

Turns out it was `tmsvg/pear-tree` -- that was the culprit. So now the insert mode mappings are working, which means two things for me: 
1) I'm no longer having this issue, hooray!
2) My setup is better, another hooray!

> What normal mode mappings would you suggest I should include in the default, other than yank additions as default action? For yank deletions and goto state specifically?

FWIW, this still seems salient. Maybe somebody does want to use normal mode -- if so, the behavior here is broken. Your mappings are perfect for insert mode, maybe make those the default for normal mode as well? NBD but might be more correct?

As far as I'm concerned this issue is safe to close, I'll leave that for you in case you want to make changes about normal mode mappings.

Thank you for your help!

**Comment by debugloop** [comment] 2023-03-26 10:43
I'll close this for now, but I will look into these mappings, normal and insert mode. It's causing too much trouble for people I think.

**Closed by debugloop** 2023-03-26 10:43 UTC

**Comment by snoblenet** [comment] 2024-03-12 22:23
Funnily enough, I ended up here because I was trying to replicate this behaviour. 

That is, I was hoping to set my default (<CR>) behaviour to 'restore to a new unsaved buffer in a vertical split'. 

Any thoughts on how to do this explicitly? 

(As in, not as an unintended side-effect of another decision.)
